image: maven:3.8.1-jdk-11-openj9

stages:          
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mvn package -DskipTests

test-job:
    stage: test
    script:
        - mvn test -DlastModGranularityMs=10000000
    artifacts:
      paths:
        - target/

